version: '2'
services:
    voltage-app:
        image: voltage
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://voltage-postgresql:5432/Voltage
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    voltage-postgresql:
        extends:
            file: postgresql.yml
            service: voltage-postgresql
